name: Build and deplay

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Build webassembly
        run: |
          cd ./src/go/
          make build

      - name: Copy WASM Lib
        run: |
          mkdir ./src/lib
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./src/lib/

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '13'

      - name: Build static assets
        run: |
          npm install
          npm run build-prod
        env:
          CI: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}