name: Build and deplay

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Build webassembly
        run: |
          cd ./src/go/
          make build

      - name: Copy WASM Lib
        run: |
          mkdir ./src/lib
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./src/lib/

